Fix #201
jnidzwetzki/bitfinex-v2-wss-api-java pull request #202
Opened 2020-12-01 13:39 UTC by hhanh00

2020-12-01 18:33 UTC, jnidzwetzki requested changes
Hi,

Thank you very much for your contribution to this project. Might it be possible to move the adjustment to the `parsePair()` method? You could set the `BitfinexCurrencyType` to `PERPETUAL` in this method directly. 

Thank you very much
   Jan

2020-12-01 18:33 UTC, jnidzwetzki commented on src/main/java/com/github/jnidzwetzki/bitfinex/v2/entity/currency/BitfinexCurrencyPair.java
> +		if (currency1.length() > 3 || currency2.length() > 3) {
Could you add this logic to the parseCurrencyType() method and set `BitfinexCurrencyType.PERPETUAL` in this case?

2020-12-02 02:53 UTC, hhanh00 commented
I'm not sure I understand what you mean. The serialization of a currency pair with ':' does not seem related to its type. For example TESTBTC:TESTUSD is a regular pair.

2020-12-02 08:49 UTC, jnidzwetzki commented
You are right. I thought `TESTBTC:TESTUSD` is also a PERPETUAL. 

Your PR is fine, thank you for your contribution.

2020-12-02 08:50 UTC, merged